[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my_local_package"
version = "0.1.0"
description = "A test package for pyodide-patterns."
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
dependencies = ["tinycss2"]
